# 网站的基本信息
site:
  tab: Shepherd's Blog 櫻の森の上を舞う # 浏览器标签栏上显示的文本
  title: Shepherd's Blog # 网站的标题
  description: My blog # 网站的描述，用于SEO等
  language: zh # 网站的语言，例如 "en" 是英文
  favicon: https://pic1.imgdb.cn/item/68d4a75dc5157e1a882dbf13.svg # 网站的图标，用于浏览器标签栏和其他地方显示
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: autumn # 主题的浅色模式
    dark: dracula # 主题的深色模式
    code: github-dark # 代码块的主题 https://expressive-code.com/guides/themes/
  date_format: ddd MMM DD YYYY # 日期格式设置，支持自定义格式
  blog: # 博客相关配置
    pageSize: 8 # 每页显示的文章数量
  menu: # 菜单配置
    # - id: home # 菜单项的唯一标识符
    #  text: Home # 菜单项显示的文本
    #  href: / # 菜单项链接的地址
    #  svg: "material-symbols:home-outline-rounded"
    #  target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
    # - id: project
    # text: Project
    # href: /project
    # svg: "material-symbols:code-blocks-outline"
    - id: log
      text: Log
      href: /log
      svg: "material-symbols:calendar-clock-outline-rounded"
      target: _self
    - id: friend
      text: Friends
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: my
      text: My
      href: /my
      target: _self
      svg: "material-symbols:person-outline-rounded"
      subItems:
        - id: anime
          text: Anime
          href: /anime
          target: _self
          svg: "material-symbols:live-tv-rounded"

    - id: link
      text: Links
      href: /link
      target: _self
      svg: "material-symbols:add-link"
      subItems:
        - id: ChatGPT
          text: ChatGPT
          href: https://chatgpt.com/
          target: _blank
          svg: ri:openai-fill
        - id: Google Gemini
          text: Google Gemini
          href: https://gemini.google.com/
          target: _blank
          svg: ri:gemini-fill

# 用户的个人信息
user:
  name: Shepherd Meng # 用户名
  site: "https://duskydream.icu" # 用户的网站链接
  avatar: https://pic1.imgdb.cn/item/65c1c9269f345e8d03080e8d.jpg # 用户头像路径
  sidebar: # 侧边栏配置
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #  ariaLabel: Support my work # 图标的可访问性标签
      #  title: Support my work # 图标的悬浮标题
      #  svg: "ri:cup-line"
      - href: "https://github.com/Duskydream"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/198625051"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/Lxzm1211"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-x-fill"
  footer:
    social:
      # - href: "https://afdian.com/a/saroprock" # 链接
      #  ariaLabel: Support my work # 图标的可访问性标签
      #  title: Support my work # 图标的悬浮标题
      #  svg: "ri:cup-line"
      - href: "https://github.com/Duskydream"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/198625051"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/Lxzm1211"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-x-fill"
